strategy:
  matrix:
    node_10_x:
      node_version: 10.x

jobs:

- job: macOS_CI_Tests
  displayName: MacOS CI Tests
  pool:
    vmImage: macOS-10.13

  steps:
  - template: ./daruk.yml


- job: ubuntu_CI_Tests
  displayName: Ubuntu  CI Tests
  pool:
    vmImage: ubuntu-16.04

  steps:
  - template: ./daruk.yml

- job: windows_CI_Tests
  displayName: Windows  CI Tests
  pool:
    vmImage: vs2017-win2016

  steps:
  - template: ./daruk.yml
